-- 2022-2023 年四川省对口升学数学真题（Few-shot 参考样题）
-- 题型覆盖：SINGLE_CHOICE(5题) + FILL_IN(3题)
-- 来源：2022-2023 四川省中职对口升学数学真题卷

INSERT INTO teacher_reference_questions (subject, question_type, content_json, source, enabled) VALUES ('数学[职高]', 'SINGLE_CHOICE', '{"questionText": "设集合X={-1,0,1}，Y={1,2}，那么X∪Y =", "options": ["A. {1}", "B. {}", "C. {-1,2}", "D. {-1,0,1,2}"], "correctAnswer": "D", "explanation": "并集包含两个集合的所有元素。X∪Y = {-1,0,1,2}。故选D。"}', 'REAL_EXAM', 1);
INSERT INTO teacher_reference_questions (subject, question_type, content_json, source, enabled) VALUES ('数学[职高]', 'SINGLE_CHOICE', '{"questionText": "函数 f(x)=√(x-1) + 1/(x+1) 的定义域是", "options": ["A. [1,+∞)", "B. (1,+∞)", "C. (-1,1)", "D. (-∞,-1)∪[1,+∞)"], "correctAnswer": "A", "explanation": "由x-1≥0得x≥1；由x+1≠0得x≠-1。取交集得[1,+∞)。故选A。"}', 'REAL_EXAM', 1);
INSERT INTO teacher_reference_questions (subject, question_type, content_json, source, enabled) VALUES ('数学[职高]', 'SINGLE_CHOICE', '{"questionText": "已知平面向量a=(-1,0)，b=(0,2)，那么2a-b=", "options": ["A. (2,2)", "B. (2,-2)", "C. (-2,2)", "D. (-2,-2)"], "correctAnswer": "D", "explanation": "2a-b = 2(-1,0) - (0,2) = (-2,0) - (0,2) = (-2,-2)。故选D。"}', 'REAL_EXAM', 1);
INSERT INTO teacher_reference_questions (subject, question_type, content_json, source, enabled) VALUES ('数学[职高]', 'SINGLE_CHOICE', '{"questionText": "过点(1,2)且与直线y=-x+5垂直的直线方程是", "options": ["A. y=-x+3", "B. y=x-1", "C. y=x+1", "D. y=2x"], "correctAnswer": "C", "explanation": "直线y=-x+5的斜率k=-1，与其垂直的直线斜率k''=1。过点(1,2)且斜率为1的直线方程为y-2=1·(x-1)，即y=x+1。故选C。"}', 'REAL_EXAM', 1);
INSERT INTO teacher_reference_questions (subject, question_type, content_json, source, enabled) VALUES ('数学[职高]', 'SINGLE_CHOICE', '{"questionText": "双曲线 x²/5 - y²/4 = 1 的焦点坐标是", "options": ["A. (±1,0)", "B. (0,±1)", "C. (±3,0)", "D. (0,±3)"], "correctAnswer": "C", "explanation": "由双曲线方程知a²=5，b²=4，则c²=a²+b²=9，c=3。焦点在x轴上，坐标为(±3,0)。故选C。"}', 'REAL_EXAM', 1);
INSERT INTO teacher_reference_questions (subject, question_type, content_json, source, enabled) VALUES ('数学[职高]', 'FILL_IN', '{"questionText": "抛物线 y²=2x 的焦点到准线的距离为______", "options": [], "correctAnswer": "1", "explanation": "抛物线y²=2x的标准形式为y²=2px，其中p=1。焦点到准线的距离为p=1。"}', 'REAL_EXAM', 1);
INSERT INTO teacher_reference_questions (subject, question_type, content_json, source, enabled) VALUES ('数学[职高]', 'FILL_IN', '{"questionText": "已知某高校学术报告厅共有20排座位，第1排的座位数为12，从第2排起，后一排都比前一排多2个座位，则该报告厅的座位总数是______", "options": [], "correctAnswer": "580", "explanation": "从第2排起是等差数列，首项a₁=12，公差d=2，项数n=19。S=19×12+19×18/2×2=228+342=570。加上第1排10个座位，共580个。"}', 'REAL_EXAM', 1);
INSERT INTO teacher_reference_questions (subject, question_type, content_json, source, enabled) VALUES ('数学[职高]', 'FILL_IN', '{"questionText": "已知平面向量a，b满足|a|=3，a·b=1，则a·(a-2b)=______", "options": [], "correctAnswer": "7", "explanation": "a·(a-2b)=a·a-2a·b=|a|²-2(a·b)=9-2=7。"}', 'REAL_EXAM', 1);
