-- 2025 年四川省对口升学语文真题（Few-shot 参考样题）
-- 题型覆盖：SINGLE_CHOICE(5题) + FILL_IN(1题) + COMPOSITION(1题)
-- 来源：四川省中职对口升学语文真题卷（2022-2025）

INSERT INTO teacher_reference_questions (subject, question_type, content_json, source, enabled) VALUES ('语文[职高]', 'SINGLE_CHOICE', '{"questionText": "下列词语中加点字的读音，全都正确的一组是", "options": ["A. 鸿鹄(hú) 粗糙(cāo) 回溯(sù) 不容小觑(qù)", "B. 迸裂(bèng) 信笺(jiān) 凝眸(móu) 解甲归田(jiě)", "C. 籼米(xiān) 埋怨(mán) 木讷(nè) 风流倜傥(tì)", "D. 拓片(tà) 商埠(bù) 缄默(jiān) 舐犊情深(shì)"], "correctAnswer": "B", "explanation": "A项''回溯''的''溯''应读sù；C项''木讷''的''讷''应读nè；D项''商埠''的''埠''应读bù。故选B。"}', 'REAL_EXAM', 1);

INSERT INTO teacher_reference_questions (subject, question_type, content_json, source, enabled) VALUES ('语文[职高]', 'SINGLE_CHOICE', '{"questionText": "下列词语中，没有错别字的一组是", "options": ["A. 家具 斗拱 披星戴月 迫不及待", "B. 坐标 帐蓬 关怀备至 豆蔻年华", "C. 松弛 痊愈 出奇不意 破釜沉舟", "D. 斑驳 缘分 金壁辉煌 厉行节约"], "correctAnswer": "A", "explanation": "B项''帐蓬''应为''帐篷''；C项''出奇不意''应为''出其不意''；D项''金壁辉煌''应为''金碧辉煌''。故选A。"}', 'REAL_EXAM', 1);

INSERT INTO teacher_reference_questions (subject, question_type, content_json, source, enabled) VALUES ('语文[职高]', 'SINGLE_CHOICE', '{"questionText": "依次填入下面各句横线处的词语，最恰当的一组是", "options": ["A. 隐蔽 惊奇 角逐", "B. 隐蔽 惊艳 博弈", "C. 隐匿 惊艳 角逐", "D. 隐匿 惊奇 博弈"], "correctAnswer": "C", "explanation": "（1）''隐匿''强调有意隐藏，比''隐蔽''更符合博物馆藏于小城的语境。（2）''惊艳''侧重于因美丽精彩而赞叹，机器人表演用''惊艳''更恰当。（3）''角逐''强调竞争较量，斗茶大赛用''角逐''更准确。故选C。"}', 'REAL_EXAM', 1);

INSERT INTO teacher_reference_questions (subject, question_type, content_json, source, enabled) VALUES ('语文[职高]', 'SINGLE_CHOICE', '{"questionText": "下列各句中加点成语的使用，不正确的一项是", "options": ["A. 发展低空经济，离不开各种各样的飞行器，我国自主研发生产的无人机已经在低空经济赛道上崭露头角。", "B. 网络纪录片《小酸村》别出心裁，带领观众探寻全国各地''独特的酸''，用酸的味觉连缀起乡村里的生活故事。", "C. 日前，天府数字经济大会在成都举行，各界嘉宾座无虚席，解析政策、洞察趋势、碰撞思想，助力四川建设全国数字经济创新发展先行省。", "D. 中国杂技剧的成功不是一蹴而就的，经历了从单个节目到主题晚会再到新型剧种的变化，体现了杂技人不断拓展艺术疆域的创新精神。"], "correctAnswer": "C", "explanation": "''座无虚席''形容观众、听众很多，主语应是会场、现场等地点，而非''嘉宾''，使用错误。故选C。"}', 'REAL_EXAM', 1);

INSERT INTO teacher_reference_questions (subject, question_type, content_json, source, enabled) VALUES ('语文[职高]', 'SINGLE_CHOICE', '{"questionText": "下列句子没有语病的一项是", "options": ["A. 今年''五一''假期，雅康高速公路天全服务区成功完成了3例无人机配送，实现西南地区高速公路无人机配送服务''破冰''，取得重大突破。", "B. 我国不断加大对林业科技的研发投入，引进并推广国外先进林业技术和管理经验，通过技术升级和模式创新，提高林业生产效率和产品质量。", "C. 四川是长江上游重要的水源涵养地，也是全球生物多样性保护重点地区，但候鸟是否在川越冬还需要有适宜的气候以及合适的栖息地等条件。", "D. 中国大熊猫金丝猴双宝文化艺术展以摄影作品、文创、史料为载体，展示''双宝''文化背后中国生物多样性保护成就和生态文明思想的重要意义，观众可以通过展览深入了解相关内容。"], "correctAnswer": "B", "explanation": "A项句式杂糅，''实现……破冰''与''取得重大突破''杂糅；C项两面对一面，''是否''与''需要有''不搭配；D项结构混乱，前后主语不一致。故选B。"}', 'REAL_EXAM', 1);

INSERT INTO teacher_reference_questions (subject, question_type, content_json, source, enabled) VALUES ('语文[职高]', 'FILL_IN', '{"questionText": "补写出下列句子中空缺的部分。（1）自牧归荑，______。匪女之为美，______。（《诗经·静女》）（2）______，孰能无惑？其为惑也，终不解矣。（韩愈《师说》）（3）故国神游，______，______。（苏轼《念奴娇·赤壁怀古》）", "options": [], "correctAnswer": "（1）洵美且异 美人之贻（2）人非生而知之者（3）多情应笑我 早生华发", "explanation": "考查名篇名句默写，注意''洵''''贻''''华发''等易错字。"}', 'REAL_EXAM', 1);

INSERT INTO teacher_reference_questions (subject, question_type, content_json, source, enabled) VALUES ('语文[职高]', 'COMPOSITION', '{"questionText": "阅读下面的文字，根据要求写作。毛竹是一种生长历程十分特别的竹子，在它生命周期的最初四五年里，即使精心种植，也不过露出三四厘米的笋尖。但是，大约第六年开始，毛竹几乎以每天30厘米的速度''飞快''生长，只用六七周就可以长到15米左右，半年时间就会长到30多米。以上材料引发了你怎样的联想和思考？请写一篇不少于700字的文章。", "options": [], "correctAnswer": "参考立意：厚积薄发、沉淀与爆发、根深才能叶茂、拒绝浮躁、坚持的力量。", "explanation": "材料作文，围绕毛竹的生长特点展开联想。核心寓意：前期在地下扎根数百米，后期快速生长——强调积累的重要性。"}', 'REAL_EXAM', 1);
