-- v104: 英语词组扩充 — 对口升学完形填空+阅读理解高频搭配 100条
-- 分类: 动词短语40 + 介词短语20 + 固定搭配40

INSERT IGNORE INTO precision_vocabulary_seeds (word, meaning, phonetic, example, frequency_rank, level) VALUES

-- ═══ 动词短语（phrasal verbs）40条 ═══
('give up','放弃','','Never give up your dream.',301,1),
('put on','穿上；上演','','Put on your coat, it is cold outside.',302,1),
('take off','脱下；起飞','','The plane will take off soon.',303,1),
('turn on','打开（电器）','','Please turn on the light.',304,1),
('turn off','关闭（电器）','','Turn off the TV before sleeping.',305,1),
('turn down','调低；拒绝','','Please turn down the music.',306,2),
('turn up','调高；出现','','He didn''t turn up at the party.',307,2),
('get up','起床','','I get up at 6 every morning.',308,1),
('get on','上车','','Get on the bus quickly.',309,1),
('get off','下车','','We got off at the next stop.',310,1),
('get along','相处','','They get along well with each other.',311,2),
('look after','照顾；照看','','Please look after my dog while I am away.',312,1),
('look for','寻找','','I am looking for my keys.',313,1),
('look forward to','期待','','I look forward to hearing from you.',314,2),
('look up','查阅；向上看','','You can look up the word in the dictionary.',315,1),
('look out','小心；注意','','Look out! There is a car coming.',316,1),
('put off','推迟','','Don''t put off today''s work till tomorrow.',317,2),
('put away','收拾；放好','','Put away your toys after playing.',318,1),
('take care of','照顾；处理','','Please take care of yourself.',319,1),
('take part in','参加','','He took part in the speech contest.',320,2),
('take place','发生；举行','','The meeting will take place next Monday.',321,2),
('give out','分发；用尽','','Please give out the papers to the class.',322,2),
('give away','赠送；泄露','','She gave away her old clothes to the poor.',323,2),
('pick up','捡起；接人','','Can you pick me up at the station?',324,1),
('pick out','挑选','','Pick out the best one for me.',325,2),
('set up','建立；设立','','They set up a new company last year.',326,2),
('set off','出发；引爆','','We set off early in the morning.',327,2),
('go on','继续','','Please go on with your story.',328,1),
('go over','复习；检查','','Let''s go over the lesson again.',329,1),
('go through','经历；翻阅','','He went through many difficulties.',330,2),
('come up with','想出','','Can you come up with a better idea?',331,2),
('run out of','用完；耗尽','','We have run out of time.',332,2),
('carry on','继续','','Carry on with your work.',333,2),
('carry out','执行；实施','','We must carry out the plan at once.',334,2),
('break down','出故障；分解','','My car broke down on the way.',335,2),
('break out','爆发','','A fire broke out last night.',336,2),
('bring up','抚养；提出','','She was brought up by her grandparents.',337,2),
('make up','编造；弥补；化妆','','Don''t make up excuses.',338,2),
('hand in','上交','','Please hand in your homework on time.',339,1),
('hand out','分发','','The teacher handed out the test papers.',340,1),

-- ═══ 介词短语 20条 ═══
('in front of','在…前面','','There is a tree in front of the house.',341,1),
('instead of','代替；而不是','','I will go instead of you.',342,2),
('because of','因为；由于','','The game was canceled because of rain.',343,1),
('according to','根据；按照','','According to the weather report, it will rain.',344,2),
('in order to','为了；以便','','He got up early in order to catch the bus.',345,2),
('in case of','万一；以防','','In case of fire, call 119.',346,2),
('in charge of','负责；管理','','Who is in charge of this project?',347,2),
('by the way','顺便说一下','','By the way, have you seen my book?',348,1),
('on the way','在路上；即将','','Spring is on the way.',349,1),
('in the way','挡路；妨碍','','Don''t stand in the way.',350,2),
('at the same time','同时','','He can read and listen at the same time.',351,1),
('from time to time','偶尔；有时','','I visit my grandparents from time to time.',352,2),
('on time','准时','','Please come to class on time.',353,1),
('in time','及时','','Will you arrive in time for the meeting?',354,1),
('at first','起初','','At first, I found English difficult.',355,1),
('at last','终于','','At last, we arrived home safely.',356,1),
('as usual','像往常一样','','He came to school late as usual.',357,1),
('in fact','事实上','','In fact, I don''t agree with you.',358,1),
('as a result','结果；因此','','He worked hard. As a result, he passed the exam.',359,2),
('in addition','此外；另外','','In addition, we need more time.',360,2),

-- ═══ 固定搭配/写作表达 40条 ═══
('pay attention to','注意','','Please pay attention to the teacher.',361,1),
('make a difference','有影响；起作用','','Your help really made a difference.',362,2),
('make progress','取得进步','','He has made great progress in English.',363,2),
('make friends','交朋友','','I like to make friends with kind people.',364,1),
('make sure','确保；确认','','Make sure you lock the door before leaving.',365,1),
('make a decision','做决定','','It is hard to make a decision now.',366,2),
('take a walk','散步','','Let''s take a walk after dinner.',367,1),
('take a rest','休息','','You look tired. Take a rest.',368,1),
('take notes','记笔记','','Don''t forget to take notes in class.',369,1),
('take action','采取行动','','We need to take action immediately.',370,2),
('have a look','看一看','','Let me have a look at your new phone.',371,1),
('have a try','试一试','','Why not have a try?',372,1),
('have a good time','玩得开心','','We had a good time at the party.',373,1),
('do one''s best','尽力','','I will do my best to help you.',374,1),
('do some shopping','购物','','I need to do some shopping this afternoon.',375,1),
('play a role in','在…中起作用','','Technology plays an important role in education.',376,2),
('catch up with','赶上','','I need to catch up with my classmates.',377,2),
('keep in touch with','与…保持联系','','We still keep in touch with each other.',378,2),
('keep up with','跟上；不落后','','It''s hard to keep up with the latest news.',379,2),
('get used to','习惯于','','I have got used to getting up early.',380,2),
('be used to','被用来','','Wood can be used to make paper.',381,2),
('used to','过去常常','','I used to play basketball every weekend.',382,1),
('be interested in','对…感兴趣','','She is interested in music.',383,1),
('be good at','擅长','','He is good at playing the piano.',384,1),
('be famous for','因…而著名','','Chengdu is famous for its food.',385,1),
('be full of','充满','','The room is full of people.',386,1),
('be proud of','为…感到骄傲','','I am proud of my son.',387,1),
('be different from','与…不同','','My school is different from yours.',388,1),
('be similar to','与…相似','','His handwriting is similar to mine.',389,2),
('be worried about','担心','','Don''t be worried about the exam.',390,1),
('think about','考虑','','I will think about your suggestion.',391,1),
('think of','想起；认为','','What do you think of this movie?',392,1),
('deal with','处理；应对','','How do you deal with stress?',393,2),
('depend on','依赖；取决于','','It depends on the weather.',394,2),
('belong to','属于','','This book belongs to me.',395,2),
('succeed in','在…上成功','','He succeeded in passing the driving test.',396,2),
('prevent … from','阻止','','The rain prevented us from going out.',397,2),
('spend … (in) doing','花时间做','','He spent two hours doing homework.',398,1),
('have difficulty in','在…有困难','','She has difficulty in learning math.',399,2),
('be busy with','忙于','','My mother is busy with housework.',400,1);
