-- ============================================================
-- v93: 英语考纲高频核心词汇 + 阅读短文种子数据
-- 词汇: 前300高频词(考纲2000词中的核心)，分3级投放
-- 阅读: 5类短文各4篇共20篇，供4周使用
-- ⚠️ 执行前必须 SET NAMES utf8mb4，防止中文乱码
-- ============================================================
SET NAMES utf8mb4;

-- ══════════════════════════════════════════
-- 高频核心 300 词（Level 1: 文本中出现频率最高的词）
-- 按词性分组: 动词/名词/形容词副词/介词连词
-- ══════════════════════════════════════════

-- 动词类（前80个）
INSERT INTO precision_vocabulary_seeds (word, meaning, phonetic, example, frequency_rank, level) VALUES
('be', '是；存在', 'bi:', 'I am a student.', 1, 1),
('have', '有', 'hæv', 'She has a book.', 2, 1),
('do', '做', 'du:', 'What do you want?', 3, 1),
('say', '说', 'seɪ', 'He said hello.', 4, 1),
('go', '去', 'ɡəʊ', 'Let\'s go home.', 5, 1),
('get', '得到；变得', 'ɡet', 'I get up at 7.', 6, 1),
('make', '制作；使', 'meɪk', 'She makes breakfast.', 7, 1),
('know', '知道', 'nəʊ', 'Do you know him?', 8, 1),
('think', '想；认为', 'θɪŋk', 'I think so.', 9, 1),
('take', '拿；花费', 'teɪk', 'It takes 10 minutes.', 10, 1),
('see', '看见', 'si:', 'I can see you.', 11, 1),
('come', '来', 'kʌm', 'Come here please.', 12, 1),
('want', '想要', 'wɒnt', 'I want an apple.', 13, 1),
('look', '看', 'lʊk', 'Look at the board.', 14, 1),
('use', '使用', 'ju:z', 'We use computers.', 15, 1),
('find', '找到；发现', 'faɪnd', 'I find it easy.', 16, 1),
('give', '给', 'ɡɪv', 'Give me a pen.', 17, 1),
('tell', '告诉', 'tel', 'Tell me your name.', 18, 1),
('work', '工作', 'wɜ:k', 'My father works hard.', 19, 1),
('call', '打电话；称呼', 'kɔ:l', 'Call me later.', 20, 1),
('try', '尝试', 'traɪ', 'Try your best.', 21, 1),
('ask', '问', 'ɑ:sk', 'May I ask a question?', 22, 1),
('need', '需要', 'ni:d', 'I need your help.', 23, 1),
('feel', '感觉', 'fi:l', 'I feel happy.', 24, 1),
('become', '变成', 'bɪˈkʌm', 'He became a teacher.', 25, 1),
('leave', '离开', 'li:v', 'I leave at 8.', 26, 1),
('put', '放', 'pʊt', 'Put it on the desk.', 27, 1),
('mean', '意思是', 'mi:n', 'What does it mean?', 28, 1),
('keep', '保持；继续', 'ki:p', 'Keep trying!', 29, 1),
('let', '让', 'let', 'Let me help you.', 30, 1),
('begin', '开始', 'bɪˈɡɪn', 'The class begins at 8.', 31, 1),
('seem', '似乎', 'si:m', 'You seem tired.', 32, 1),
('help', '帮助', 'help', 'Can you help me?', 33, 1),
('show', '展示', 'ʃəʊ', 'Show me the way.', 34, 1),
('hear', '听见', 'hɪə', 'Can you hear me?', 35, 1),
('play', '玩；播放', 'pleɪ', 'Let\'s play basketball.', 36, 1),
('run', '跑', 'rʌn', 'He runs fast.', 37, 1),
('move', '移动', 'mu:v', 'Please move your chair.', 38, 1),
('live', '生活；居住', 'lɪv', 'I live in Chengdu.', 39, 1),
('believe', '相信', 'bɪˈli:v', 'I believe you.', 40, 1),
('bring', '带来', 'brɪŋ', 'Bring your book tomorrow.', 41, 1),
('happen', '发生', 'ˈhæpən', 'What happened?', 42, 1),
('write', '写', 'raɪt', 'Write your name here.', 43, 1),
('provide', '提供', 'prəˈvaɪd', 'We provide food.', 44, 1),
('sit', '坐', 'sɪt', 'Please sit down.', 45, 1),
('stand', '站；忍受', 'stænd', 'Stand up please.', 46, 1),
('lose', '丢失；输', 'lu:z', 'I lost my key.', 47, 1),
('pay', '付钱', 'peɪ', 'I paid 20 yuan.', 48, 1),
('meet', '遇见；开会', 'mi:t', 'Nice to meet you.', 49, 1),
('include', '包括', 'ɪnˈklu:d', 'The price includes lunch.', 50, 1),
('continue', '继续', 'kənˈtɪnju:', 'Please continue reading.', 51, 1),
('set', '设置；放', 'set', 'Set the table please.', 52, 1),
('learn', '学习', 'lɜ:n', 'We learn English.', 53, 1),
('change', '改变', 'tʃeɪndʒ', 'Things change.', 54, 1),
('lead', '领导；导致', 'li:d', 'This road leads to school.', 55, 1),
('understand', '理解', 'ˌʌndəˈstænd', 'Do you understand?', 56, 1),
('watch', '观看', 'wɒtʃ', 'We watch TV.', 57, 1),
('follow', '跟随', 'ˈfɒləʊ', 'Follow me.', 58, 1),
('stop', '停止', 'stɒp', 'Stop talking!', 59, 1),
('create', '创造', 'kriˈeɪt', 'Create a new file.', 60, 1),
('speak', '说话', 'spi:k', 'She speaks English well.', 61, 1),
('read', '读', 'ri:d', 'Read the text.', 62, 1),
('allow', '允许', 'əˈlaʊ', 'Smoking is not allowed.', 63, 1),
('add', '增加', 'æd', 'Add some sugar.', 64, 1),
('spend', '花费(钱/时间)', 'spend', 'I spend 2 hours studying.', 65, 1),
('grow', '成长；种植', 'ɡrəʊ', 'Plants grow quickly.', 66, 1),
('open', '打开', 'ˈəʊpən', 'Open the door.', 67, 1),
('walk', '走', 'wɔ:k', 'I walk to school.', 68, 1),
('win', '赢', 'wɪn', 'We won the game.', 69, 1),
('offer', '提供', 'ˈɒfə', 'He offered me a job.', 70, 1),
('remember', '记住', 'rɪˈmembə', 'Remember the words.', 71, 1),
('love', '爱', 'lʌv', 'I love my family.', 72, 1),
('consider', '考虑', 'kənˈsɪdə', 'Consider this idea.', 73, 1),
('appear', '出现', 'əˈpɪə', 'He appeared at the door.', 74, 1),
('buy', '买', 'baɪ', 'I bought a new pen.', 75, 1),
('wait', '等待', 'weɪt', 'Wait a moment.', 76, 1),
('serve', '服务', 'sɜ:v', 'Breakfast is served.', 77, 1),
('die', '死', 'daɪ', 'The flower died.', 78, 1),
('send', '发送', 'send', 'Send me an email.', 79, 1),
('expect', '期待；预期', 'ɪkˈspekt', 'I expect good results.', 80, 1);

-- 名词类（前60个）
INSERT INTO precision_vocabulary_seeds (word, meaning, phonetic, example, frequency_rank, level) VALUES
('time', '时间', 'taɪm', 'What time is it?', 81, 1),
('people', '人们', 'ˈpi:pl', 'Many people live here.', 82, 1),
('way', '方式；路', 'weɪ', 'Is this the right way?', 83, 1),
('day', '天；日', 'deɪ', 'Have a nice day!', 84, 1),
('man', '男人', 'mæn', 'The man is tall.', 85, 1),
('woman', '女人', 'ˈwʊmən', 'She is a kind woman.', 86, 1),
('child', '孩子', 'tʃaɪld', 'The child is playing.', 87, 1),
('world', '世界', 'wɜ:ld', 'The world is big.', 88, 1),
('school', '学校', 'sku:l', 'I go to school.', 89, 1),
('country', '国家', 'ˈkʌntri', 'China is a great country.', 90, 1),
('hand', '手', 'hænd', 'Wash your hands.', 91, 1),
('part', '部分', 'pɑ:t', 'This is the best part.', 92, 1),
('place', '地方', 'pleɪs', 'This is a nice place.', 93, 1),
('case', '情况；案例', 'keɪs', 'In that case, I agree.', 94, 1),
('week', '周', 'wi:k', 'See you next week.', 95, 1),
('number', '数字；数量', 'ˈnʌmbə', 'A large number of students.', 96, 1),
('group', '组', 'ɡru:p', 'Work in groups.', 97, 1),
('problem', '问题', 'ˈprɒbləm', 'No problem.', 98, 1),
('fact', '事实', 'fækt', 'In fact, he is right.', 99, 1),
('question', '问题', 'ˈkwestʃən', 'Do you have questions?', 100, 1),
('life', '生活；生命', 'laɪf', 'Enjoy your life.', 101, 1),
('story', '故事', 'ˈstɔ:ri', 'Tell me a story.', 102, 1),
('example', '例子', 'ɪɡˈzɑ:mpl', 'For example.', 103, 1),
('money', '钱', 'ˈmʌni', 'I need some money.', 104, 1),
('water', '水', 'ˈwɔ:tə', 'Drink some water.', 105, 1),
('food', '食物', 'fu:d', 'The food is delicious.', 106, 1),
('family', '家庭', 'ˈfæməli', 'I love my family.', 107, 1),
('home', '家', 'həʊm', 'Go home now.', 108, 1),
('name', '名字', 'neɪm', 'What is your name?', 109, 1),
('friend', '朋友', 'frend', 'He is my best friend.', 110, 1),
('student', '学生', 'ˈstju:dnt', 'I am a student.', 111, 1),
('teacher', '老师', 'ˈti:tʃə', 'Our teacher is kind.', 112, 1),
('reason', '原因', 'ˈri:zn', 'What is the reason?', 113, 1),
('change', '改变；零钱', 'tʃeɪndʒ', 'Here is your change.', 114, 1),
('interest', '兴趣', 'ˈɪntrəst', 'I have interest in music.', 115, 1),
('order', '顺序；命令', 'ˈɔ:də', 'In order to succeed.', 116, 1),
('power', '力量；权力', 'ˈpaʊə', 'Knowledge is power.', 117, 1),
('head', '头', 'hed', 'I have a headache.', 118, 1),
('eye', '眼睛', 'aɪ', 'Open your eyes.', 119, 1),
('point', '点；意义', 'pɔɪnt', 'What is your point?', 120, 1),
('mind', '思想；介意', 'maɪnd', 'Never mind.', 121, 1),
('hour', '小时', 'ˈaʊə', 'One hour is 60 minutes.', 122, 1),
('morning', '早晨', 'ˈmɔ:nɪŋ', 'Good morning!', 123, 1),
('result', '结果', 'rɪˈzʌlt', 'The result is good.', 124, 1),
('job', '工作', 'dʒɒb', 'I found a job.', 125, 1),
('information', '信息', 'ˌɪnfəˈmeɪʃn', 'More information please.', 126, 1),
('book', '书', 'bʊk', 'Read this book.', 127, 1),
('room', '房间', 'ru:m', 'This is my room.', 128, 1),
('door', '门', 'dɔ:', 'Close the door.', 129, 1),
('light', '灯；光', 'laɪt', 'Turn on the light.', 130, 1),
('computer', '电脑', 'kəmˈpju:tə', 'I use a computer.', 131, 1),
('idea', '想法', 'aɪˈdɪə', 'Good idea!', 132, 1),
('end', '结束；末端', 'end', 'The end of the story.', 133, 1),
('year', '年', 'jɪə', 'Happy New Year!', 134, 1),
('thing', '事情；东西', 'θɪŋ', 'Many things to do.', 135, 1),
('word', '单词', 'wɜ:d', 'Learn new words.', 136, 1),
('kind', '种类', 'kaɪnd', 'What kind of music?', 137, 1),
('lot', '许多', 'lɒt', 'A lot of people.', 138, 1),
('side', '边', 'saɪd', 'On the other side.', 139, 1),
('city', '城市', 'ˈsɪti', 'I live in a big city.', 140, 1);
