-- v98: 英语词汇第三批扩充 100词 (259→~360)
-- 形容词/副词/介词/连词 + 对口升学高频补充词
INSERT IGNORE INTO precision_vocabulary_seeds (word, meaning, phonetic, example, frequency_rank, level) VALUES
-- 形容词/副词 (50个)
('able','有能力的','/ˈeɪbəl/','I am able to do it.',151,2),
('angry','生气的','/ˈæŋɡri/','He was angry.',152,1),
('bad','坏的','/bæd/','It is bad.',153,1),
('beautiful','美丽的','/ˈbjuːtɪfəl/','Beautiful flowers.',154,2),
('big','大的','/bɪɡ/','A big house.',155,1),
('busy','忙碌的','/ˈbɪzi/','I am busy.',156,1),
('careful','小心的','/ˈkerfəl/','Be careful!',157,2),
('cheap','便宜的','/tʃiːp/','It is cheap.',158,1),
('clean','干净的','/kliːn/','Clean water.',159,1),
('clear','清晰的','/klɪr/','Clear explanation.',160,2),
('cold','冷的','/koʊld/','Cold weather.',161,1),
('comfortable','舒服的','/ˈkʌmftəbəl/','Comfortable chair.',162,2),
('common','常见的','/ˈkɑːmən/','Common problem.',163,2),
('correct','正确的','/kəˈrekt/','Correct answer.',164,1),
('dangerous','危险的','/ˈdeɪndʒərəs/','Dangerous road.',165,2),
('different','不同的','/ˈdɪfərənt/','Different ideas.',166,1),
('difficult','困难的','/ˈdɪfɪkəlt/','A difficult test.',167,1),
('easy','容易的','/ˈiːzi/','Easy question.',168,1),
('expensive','昂贵的','/ɪkˈspensɪv/','Expensive car.',169,2),
('famous','著名的','/ˈfeɪməs/','Famous writer.',170,2),
('fast','快的','/fæst/','Fast runner.',171,1),
('free','自由的','/friː/','Free time.',172,1),
('full','满的','/fʊl/','Full of people.',173,1),
('glad','高兴的','/ɡlæd/','I am glad.',174,1),
('good','好的','/ɡʊd/','Good job!',175,1),
('happy','快乐的','/ˈhæpi/','Happy birthday!',176,1),
('hard','困难的','/hɑːrd/','Hard work.',177,1),
('healthy','健康的','/ˈhelθi/','Eat healthy.',178,2),
('heavy','重的','/ˈhɛvi/','Heavy box.',179,1),
('high','高的','/haɪ/','High mountain.',180,1),
('important','重要的','/ɪmˈpɔːrtənt/','Important meeting.',181,1),
('interested','感兴趣的','/ˈɪntrəstɪd/','I am interested.',182,2),
('kind','友善的','/kaɪnd/','A kind person.',183,1),
('large','大的','/lɑːrdʒ/','Large room.',184,1),
('last','最后的','/læst/','Last chance.',185,1),
('late','晚的','/leɪt/','I am late.',186,1),
('little','小的','/ˈlɪtəl/','Little girl.',187,1),
('long','长的','/lɔːŋ/','Long time.',188,1),
('loud','大声的','/laʊd/','Loud music.',189,1),
('low','低的','/loʊ/','Low price.',190,1),
('necessary','必要的','/ˈnesəseri/','Is it necessary?',191,2),
('new','新的','/njuː/','New book.',192,1),
('next','下一个','/nekst/','Next week.',193,1),
('nice','好的','/naɪs/','Nice weather.',194,1),
('noisy','吵闹的','/ˈnɔɪzi/','Noisy street.',195,1),
('old','老的','/oʊld/','Old friend.',196,1),
('popular','流行的','/ˈpɑːpjələr/','Popular song.',197,2),
('poor','贫穷的','/pʊr/','Poor family.',198,1),
('possible','可能的','/ˈpɑːsəbəl/','Is it possible?',199,2),
('proper','适当的','/ˈprɑːpər/','Proper way.',200,2),
-- 介词/连词/代词 (26个)
('about','关于','/əˈbaʊt/','Talk about it.',201,1),
('above','在上面','/əˈbʌv/','Above the desk.',202,2),
('across','穿过','/əˈkrɔːs/','Walk across street.',203,2),
('after','在...之后','/ˈæftər/','After school.',204,1),
('against','反对','/əˈɡenst/','Fight against it.',205,2),
('along','沿着','/əˈlɔːŋ/','Walk along the river.',206,2),
('among','在...之中','/əˈmʌŋ/','Among friends.',207,2),
('before','在...之前','/bɪˈfɔːr/','Before class.',208,1),
('behind','在...后面','/bɪˈhaɪnd/','Behind the door.',209,2),
('below','在...下面','/bɪˈloʊ/','Below the table.',210,2),
('beside','在...旁边','/bɪˈsaɪd/','Sit beside me.',211,2),
('between','在...之间','/bɪˈtwiːn/','Between A and B.',212,1),
('during','在...期间','/ˈdʊrɪŋ/','During the class.',213,2),
('except','除了','/ɪkˈsept/','Except you.',214,2),
('inside','在...里面','/ɪnˈsaɪd/','Inside the box.',215,1),
('outside','在外面','/aʊtˈsaɪd/','Outside the room.',216,1),
('since','自从','/sɪns/','Since 2020.',217,2),
('through','通过','/θruː/','Through the window.',218,2),
('toward','朝向','/tɔːrd/','Walk toward me.',219,2),
('under','在...下面','/ˈʌndər/','Under the bed.',220,1),
('until','直到','/ʌnˈtɪl/','Until tomorrow.',221,2),
('without','没有','/wɪˈðaʊt/','Without you.',222,1),
('however','然而','/haʊˈevər/','However, it is true.',223,2),
('although','虽然','/ɔːlˈðoʊ/','Although it rained.',224,2),
('therefore','因此','/ˈðerfɔːr/','Therefore, we go.',225,2),
('unless','除非','/ʌnˈles/','Unless you try.',226,2),
-- 数字/时间/量词 (24个)
('hundred','百','/ˈhʌndrəd/','One hundred.',227,1),
('thousand','千','/ˈθaʊzənd/','Two thousand.',228,1),
('million','百万','/ˈmɪljən/','One million.',229,2),
('once','一次','/wʌns/','Once upon a time.',230,1),
('twice','两次','/twaɪs/','Think twice.',231,1),
('today','今天','/təˈdeɪ/','Today is Monday.',232,1),
('tomorrow','明天','/təˈmɔːroʊ/','See you tomorrow.',233,1),
('yesterday','昨天','/ˈjestərdeɪ/','Yesterday was Sunday.',234,1),
('always','总是','/ˈɔːlweɪz/','Always be honest.',235,1),
('never','从不','/ˈnevər/','Never give up.',236,1),
('often','经常','/ˈɔːfən/','I often read.',237,1),
('seldom','很少','/ˈseldəm/','I seldom eat out.',238,2),
('sometimes','有时','/ˈsʌmtaɪmz/','Sometimes I walk.',239,1),
('usually','通常','/ˈjuːʒuəli/','I usually get up at 7.',240,1),
('already','已经','/ɔːlˈredi/','I already finished.',241,2),
('still','仍然','/stɪl/','I still love you.',242,1),
('yet','还','/jet/','Not yet.',243,1),
('just','刚刚','/dʒʌst/','I just arrived.',244,1),
('very','很','/ˈveri/','Very good.',245,1),
('quite','相当','/kwaɪt/','Quite interesting.',246,2),
('too','太','/tuː/','Too expensive.',247,1),
('enough','足够','/ɪˈnʌf/','Enough is enough.',248,1),
('nearly','几乎','/ˈnɪrli/','Nearly finished.',249,2),
('almost','几乎','/ˈɔːlmoʊst/','Almost there.',250,2);
